//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemplos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VendasEntities : DbContext
    {
        public VendasEntities()
            : base("name=VendasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_cat_categoria> tb_cat_categoria { get; set; }
        public virtual DbSet<tb_cid_cidade> tb_cid_cidade { get; set; }
        public virtual DbSet<tb_cli_cliente> tb_cli_cliente { get; set; }
        public virtual DbSet<tb_for_fornecedor> tb_for_fornecedor { get; set; }
        public virtual DbSet<tb_fun_funcionario> tb_fun_funcionario { get; set; }
        public virtual DbSet<tb_ive_item_venda> tb_ive_item_venda { get; set; }
        public virtual DbSet<tb_pai_pais> tb_pai_pais { get; set; }
        public virtual DbSet<tb_pro_produto> tb_pro_produto { get; set; }
        public virtual DbSet<tb_tra_transportadora> tb_tra_transportadora { get; set; }
        public virtual DbSet<tb_ven_venda> tb_ven_venda { get; set; }
    }
}
