//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemploes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cid_cidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cid_cidade()
        {
            this.tb_cli_cliente = new HashSet<tb_cli_cliente>();
            this.tb_for_fornecedor = new HashSet<tb_for_fornecedor>();
            this.tb_fun_funcionario = new HashSet<tb_fun_funcionario>();
            this.tb_ven_venda = new HashSet<tb_ven_venda>();
        }
    
        public long cid_codigo { get; set; }
        public string cid_nome { get; set; }
        public Nullable<long> pai_codigo { get; set; }
    
        public virtual tb_pai_pais tb_pai_pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cli_cliente> tb_cli_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_for_fornecedor> tb_for_fornecedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fun_funcionario> tb_fun_funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ven_venda> tb_ven_venda { get; set; }
    }
}
