//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemploes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cli_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cli_cliente()
        {
            this.tb_ven_venda = new HashSet<tb_ven_venda>();
        }
    
        public string cli_codigo { get; set; }
        public string cli_nome { get; set; }
        public string cli_contato { get; set; }
        public string cli_cargo { get; set; }
        public string cli_endereco { get; set; }
        public Nullable<long> cid_codigo { get; set; }
        public string cli_caixa_postal { get; set; }
        public Nullable<long> pai_codigo { get; set; }
        public string cli_telefone { get; set; }
        public string cli_fax { get; set; }
    
        public virtual tb_cid_cidade tb_cid_cidade { get; set; }
        public virtual tb_pai_pais tb_pai_pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ven_venda> tb_ven_venda { get; set; }
    }
}
