//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemplos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cat_categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cat_categoria()
        {
            this.tb_pro_produto = new HashSet<tb_pro_produto>();
        }
    
        public int cat_codigo { get; set; }
        public string cat_nome { get; set; }
        public string cat_descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pro_produto> tb_pro_produto { get; set; }
    }
}
