//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemploes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_for_fornecedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_for_fornecedor()
        {
            this.tb_pro_produto = new HashSet<tb_pro_produto>();
        }
    
        public int frn_codigo { get; set; }
        public string frn_nome { get; set; }
        public string frn_contato { get; set; }
        public string frn_cargo { get; set; }
        public string frn_endereco { get; set; }
        public Nullable<long> cid_codigo { get; set; }
        public string frn_codigo_postal { get; set; }
        public Nullable<long> pai_codigo { get; set; }
        public string frn_telefone { get; set; }
        public string frn_fax { get; set; }
        public string frn_site { get; set; }
    
        public virtual tb_cid_cidade tb_cid_cidade { get; set; }
        public virtual tb_pai_pais tb_pai_pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pro_produto> tb_pro_produto { get; set; }
    }
}
