//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemploes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fun_funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_fun_funcionario()
        {
            this.tb_ven_venda = new HashSet<tb_ven_venda>();
        }
    
        public int fun_codigo { get; set; }
        public string fun_sobrenome { get; set; }
        public string fun_nome { get; set; }
        public string fun_cargo { get; set; }
        public string fun_titulo { get; set; }
        public Nullable<System.DateTime> fun_nascimento { get; set; }
        public Nullable<System.DateTime> fun_admissao { get; set; }
        public string fun_endereco { get; set; }
        public Nullable<long> cid_codigo { get; set; }
        public Nullable<long> pai_codigo { get; set; }
        public string fun_telefone { get; set; }
        public string fun_ramal { get; set; }
        public string fun_observacao { get; set; }
        public string fun_login { get; set; }
        public Nullable<int> fun_senha { get; set; }
    
        public virtual tb_cid_cidade tb_cid_cidade { get; set; }
        public virtual tb_pai_pais tb_pai_pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ven_venda> tb_ven_venda { get; set; }
    }
}
