//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemplos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ive_item_venda
    {
        public long ive_codigo { get; set; }
        public int ven_codigo { get; set; }
        public int pro_codigo { get; set; }
        public decimal ive_valor_unitario { get; set; }
        public short ive_quantidade { get; set; }
        public float ive_desconto { get; set; }
    
        public virtual tb_ven_venda tb_ven_venda { get; set; }
    }
}
