//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemploes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ven_venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ven_venda()
        {
            this.tb_ive_item_venda = new HashSet<tb_ive_item_venda>();
        }
    
        public int ven_codigo { get; set; }
        public string cli_codigo { get; set; }
        public Nullable<int> fun_codigo { get; set; }
        public Nullable<System.DateTime> ven_data_pedido { get; set; }
        public Nullable<System.DateTime> ven_prazo_entrega { get; set; }
        public Nullable<System.DateTime> ven_data_envio { get; set; }
        public Nullable<int> tra_codigo { get; set; }
        public Nullable<decimal> frete { get; set; }
        public string ven_local_entrega { get; set; }
        public string ven_endereco { get; set; }
        public Nullable<long> cid_codigo { get; set; }
        public string ven_caixa_postal { get; set; }
        public Nullable<long> pai_codigo { get; set; }
    
        public virtual tb_cid_cidade tb_cid_cidade { get; set; }
        public virtual tb_cli_cliente tb_cli_cliente { get; set; }
        public virtual tb_fun_funcionario tb_fun_funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ive_item_venda> tb_ive_item_venda { get; set; }
        public virtual tb_pai_pais tb_pai_pais { get; set; }
        public virtual tb_tra_transportadora tb_tra_transportadora { get; set; }
    }
}
